export type UpdateType =
    | `EXPERIMENTS`
    | `EXPERIMENT`
    | `AGGREGATE_EXPERIMENTS`
    | `AGGREGATE_EXPERIMENT`
    | `OUTPUTS`
    | `AGGREGATE_OUTPUTS`
    | `TIMEGRAPH`
    | `AGGREGATE_TIMEGRAPH`
    | `XYTREE`
    | `AGGREGATE_XYTREE`
    | `DATATREE`
    | `AGGREGATE_DATATREE`;
